### ISSUE TITLE
Cannot "vision pick and place" after update RPi image 4.1.0 and Pyniryo 1.1.2

### ISSUE THREAD

**Issue by nqduy35** [NiryoRobotics/pyniryo#4]
Hello, after updating the RPI image 4.1.0 and Pyniryo 1.1.2 for my Niryo Ned, then my program pick and place with vision does not work anymore. Before the update, everything is ok. I have tried to test other basic pick and place with vision examples proposed by [your tutorial](https://docs.niryo.com/dev/pyniryo/v1.1.2/en/source/examples/examples_vision.html) but they don't work either. Here is the error: 

` ret = niryo_robot.get_target_pose_from_cam(workspace_name,
  File "/home/computer/.local/lib/python3.8/site-packages/pyniryo/api/tcp_client.py", line 1418, in get_target_pose_from_cam
    data_array = self.__send_n_receive(Command.GET_TARGET_POSE_FROM_CAM,
  File "/home/computer/.local/lib/python3.8/site-packages/pyniryo/api/tcp_client.py", line 152, in __send_n_receive
    return self.__receive_answer(with_payload=with_payload)
  File "/home/computer/.local/lib/python3.8/site-packages/pyniryo/api/tcp_client.py", line 138, in __receive_answer
    raise NiryoRobotException("Command KO : {}".format(received_dict["message"]))
pyniryo.api.exceptions.NiryoRobotException: Command KO : An error occured while executing the last command : Error Code : -303
Message : u'myworkspace'`

Edit: I tried to downgrade pyniryo to version 1.1.1 but there is an error "7 parameters expected but 6 was given". So the version 1.1.1 is not working too.

**Comment by ValentinPitre** [comment]
Did you create the **_myworkspace_** workspace in your robot?

**Comment by nqduy35** [comment]
Hello, before the update, everything worked fine. It also means that I had configured the workspace correctly. So I guess it was not the problem. 

My solution: I finally downgraded the image to v4.0.1 and everything works as before now. I will close the topic here. Thank 
you.
