### ISSUE TITLE
Impossible to call clear_collision_detected()

### ISSUE THREAD

**Issue by thisisafakegit** [NiryoRobotics/pyniryo#6]
Hello. I'm using a NIRYO Ned 2 Arm with a camera and a grasper. 

After some time using the robot with the python API I receive the following error:
```json
{
    "command": "MOVE_POSE",
    "list_ret_param": [],
    "message": "An error occured while executing the last command : clear_collision_detected() must be called before attempting a new move command",
    "status": "KO"
}
```

The line that triggered this is the `robot.move_to_home_pose()` function. Unfortunately, the only way I found to retake command of the arm is to reboot it. I would like to know if there is any other way since the function `clear_collision_detected()` does not exist on this API.

Cheers

**Comment by ralfgerlich** [comment]
I came across the same issue today. It seems that the tcp_server does not support calling this function, so there is no way to do this from pyniryo, currently. I would second the request for adding that. However, given that Niryo seems to be working on pyniryo2, I do not see much of a chance of this happening.

**Comment by jmottier-niryo** [comment]
Hello, this is a known issue and it will be fixed in the next release
